application:
  name:
  auth:
    token:
      secretkey:
      issuer :
      access-token-ttl-millis:
      refresh-token-ttl-millis:
    cookie:
      refresh-token-cookie-name:
      refresh-token-cookie-path:
      refresh-token-cookie-max-age:
      refresh-token-cookie-same-site:
      refresh-token-cookie-domain:
    cors:
      allowed-origins:
      allowed-methods:
      allowed-headers:
      exposed-headers:
      max-age:
      url-source:


springdoc:
  api-docs:
    path:
  swagger-ui:
    path:
  info:
    title:
    version:
    description:

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  output:
    ansi:
      enabled:
  servlet:
    multipart:
      max-file-size:
      max-request-size:
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:

logging:
  level:
    org.hibernate.SQL:

file:
  upload-dir:
    profile:
    article:
  logo:

server:
  port:
  ssl:
    enabled:
    key-store:
    key-store-password:
    key-store-type:
    key-alias: